MarfiB2BCPETemplateBundle_homepage:
    pattern:  /
    defaults: { _controller: MarfiB2BCPETemplateBundle:Default:index, name: noname }

# route definita dentro index.html.twig per gestire il POST del form per la scelta del modello di CPE
cpe_model_check:
    pattern:  /
    defaults: { _controller: MarfiB2BCPETemplateBundle:Default:index }


# route definita dentro simcallsForm.html.twig per gestire il POST del form per il setting delle sim calls
simcalls:
    pattern:  /Model/simcalls
    defaults: { _controller: MarfiB2BCPETemplateBundle:Simcalls:simcalls, filename: empty }

# route definita dentro MultipointController per passare alla schermata single numbe
singlenumber:
    pattern:  /Model/singlenumber
    defaults: { _controller: MarfiB2BCPETemplateBundle:Singlenumber:index}

# route definita dentro SimcalleController per passare alla schermata multipoint,
multipoint:
    pattern:  /Model/multipoint
    defaults: { _controller: MarfiB2BCPETemplateBundle:Multipoint:index}

# route definita dentro MultipointController per passare alla schermata single numbe
newpui:
    pattern:  /Model/newpui
    defaults: { _controller: MarfiB2BCPETemplateBundle:Newpui:index}

multinumber:
    pattern:  /Model/multinumber
    defaults: { _controller: MarfiB2BCPETemplateBundle:Multinumber:index}

gnr:
    pattern:  /Model/gnr
    defaults: { _controller: MarfiB2BCPETemplateBundle:Gnr:index}

fax:
    pattern:  /Model/fax
    defaults: { _controller: MarfiB2BCPETemplateBundle:Fax:index}

faxcli:
    pattern:  /Model/faxcli/{howmany}
    defaults: { _controller: MarfiB2BCPETemplateBundle:Faxcli:index, howmany: 0}

pos:
    pattern:  /Model/pos
    defaults: { _controller: MarfiB2BCPETemplateBundle:Pos:index}

poscli:
    pattern:  /Model/poscli/{howmany}
    defaults: { _controller: MarfiB2BCPETemplateBundle:Poscli:index, howmany: 0}

prefixportlist:
    pattern:  /Model/prefixportlist
    defaults: { _controller: MarfiB2BCPETemplateBundle:Prefixportlist:index}

prefixcreation:
    pattern:  /Model/prefixcreation/{portname}
    defaults: { _controller: MarfiB2BCPETemplateBundle:Prefixcreation:index, portname: empty}

pobri:
    pattern:  /Model/pobri/
    defaults: { _controller: MarfiB2BCPETemplateBundle:Pobri:index}

backup:
    pattern:  /Model/backup/
    defaults: { _controller: MarfiB2BCPETemplateBundle:Backup:index}

#route richiamata dal redirect dentro il defaultController dopo aver scelto il modello
modelroute:
    pattern:  /Model/{filename}
    defaults: { _controller: MarfiB2BCPETemplateBundle:Model:index, filename: empty }
    

# route definita dentro customerForm.html.twig per gestire il POST del form per il setting del customerID
customerid_check:
    pattern:  /Model/{filename}
    defaults: { _controller: MarfiB2BCPETemplateBundle:Model:index, filename: empty }

summary:
    pattern:  /Model/summary/
    defaults: { _controller: MarfiB2BCPETemplateBundle:Summary:index}
