parameters:
#    marfi_b2_bcpe_template.example.class: Marfi\B2BCPETemplateBundle\Example

services:
#    marfi_b2_bcpe_template.example:
#        class: %marfi_b2_bcpe_template.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
