# Marfi/B2BCPETemplateBundle/Resources/config/validation.yml

Marfi\B2BCPETemplateBundle\Entity\SingleNumberTask:
      properties:
        portListNames:
            - NotBlank: {message: "You must select at least one port"} 
      getters:
        E164:
          - "True": {message: "Not a valid E164 number, please insert again valid Italian PUI number. Format: 0<local_area><customer_number>"}
        BindOk:
          - "True": {message: "If you select bonding aggregation, at least two ports must be selected - If you don't select bonding aggregation, only one port must be selected"}
        SingleNumberUnused:
          - "True": {message: "Number (PUI) already configured, you cannot use it!!!"}
        
Marfi\B2BCPETemplateBundle\Entity\GnrTask:
      properties:
        portListNames:
            - NotBlank: {message: "You must select at least one port"} 
      getters:
        RootNumberValid:
          - "True": {message: "Not a valid root number, please insert again valid Italian PUI number min 5 digits max 11 digits. Format: 0<local_area><customer_root>"}
        BindOk:
          - "True": {message: "If you select bonding aggregation, at least two ports must be selected - If you don't select bonding aggregation, only one port must be selected"}
        DidOk:
          - "True": {message: "If you select DID, you must set digits extension - If you don't select DID, don't insert any digit extension"}
        CliAlreadyUsed:
          - "True": {message: "Number (PUI) already configured, please check it!!"}
        ExtensionOk:
           - "True": {message: "You cannot configure more that 4 digit extensions!"}

Marfi\B2BCPETemplateBundle\Entity\MultinumberTask:
      properties:
        portListNames:
            - NotBlank: {message: "You must select at least one port"} 
      getters:
        CliListOk:
          - "True": {message: "Not valid cli number, please insert again valid Italian PUI number (min 5 digits max 11 digits. Format: 0<local_area><customer_root>)"}				
        BindOk:
          - "True": {message: "If you select bonding aggregation, at least two ports must be selected - If you don't select bonding aggregation, only one port must be selected"}
        CliAlreadyUsed:
          - "True": {message: "Number (PUI) already configured, please check it!!"}
           
Marfi\B2BCPETemplateBundle\Entity\EnableServiceTask:
      properties:
        howMany:
        - NotBlank: {message: "You must define how many CLI will have fax!!"}
        enable:
        - NotBlank: {message: "You must enable it!!"}
      getters:
        HowManyOk:
          - "True": {message: "You cannot have so many CLI - not enought CLI available!!"}

Marfi\B2BCPETemplateBundle\Entity\MultipointTask:
      properties:
        portListNames:
            - NotBlank: {message: "You must select at least one port"} 
            
Marfi\B2BCPETemplateBundle\Entity\PortlistTask:
      properties:
        portListNames:
            - NotBlank: {message: "You must select at least one port"} 
            
Marfi\B2BCPETemplateBundle\Entity\PrefixcreationTask:
      getters:
        FormOk:
          - "True": {message: "Check prefix - must be a digit number with max 4 digits - check all type are configured for inserted prefixes!!"}
            
